sudo: required

language: java

services:
  - docker

before_install:
  - docker-compose up -d

script: >
  testResults="echo $(curl -i http://localhost/tests/index.cfm?format=travis)";
  echo "$testResults";
  if grep -i "http/1.1 500" <<< $testResults; then exit 1; fi